#  Tarot System - AI Service API Endpoints
"""
API endpoints for AI service integration
"""

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional
from motor.motor_asyncio import AsyncIOMotorCollection
import structlog

from app.core.database import get_ai_training_data_collection, get_tarot_cards_collection
from app.services.ai_service import AIService
from app.services.harness_router import HarnessRouterService

logger = structlog.get_logger()
router = APIRouter()

class LLMConfig(BaseModel):
    provider: str
    api_key: str
    model: str

class GenerateReadingRequest(BaseModel):
    question: str
    cards: list
    reading_type: Optional[str] = None
    reading_detail: Optional[str] = None  # "quick" | "full"
    llm_config: Optional[LLMConfig] = None
    class Config:
        json_schema_extra = {
            "example": {
                "question": "Tôi nên tập trung điều gì trong 3 tháng tới?",
                "cards": [
                    {"id": "689483ffac8d159543c982d4", "name": "King of Pentacles", "name_vi": "Vua Đồng Tiền"},
                    {"id": "689483ffac8d159543c982d3", "name": "Queen of Pentacles", "name_vi": "Hoàng Hậu Đồng Tiền"},
                    {"id": "689483ffac8d159543c982d2", "name": "Knight of Pentacles", "name_vi": "Hiệp Sĩ Đồng Tiền"}
                ],
                "reading_type": "general",
                "reading_detail": "quick"
            }
        }


class AIReadingResult(BaseModel):
    ai_response: str
    ai_summary: Optional[str] = None
    ai_advice: Optional[str] = None
    cards_interpreted: int
    response_length: int
    model_used: str
    generated_at: str


@router.post(
    "/generate-reading",
    response_model=AIReadingResult,
    summary="Generate AI tarot reading",
    description="Generate a tarot reading from a question and drawn cards using the configured LLM.",
)
async def generate_reading(
    payload: GenerateReadingRequest,
    collection: AsyncIOMotorCollection = Depends(get_ai_training_data_collection),
    cards_collection: AsyncIOMotorCollection = Depends(get_tarot_cards_collection),
):
    """Generate AI-powered tarot reading.

    Expects JSON body: {"question": str, "cards": list, "reading_type": optional}
    """
    try:
        # Enrich cards with full data if possible
        enriched_cards = []
        for c in payload.cards:
            try:
                card_id = c.get("id") or c.get("_id")
                if card_id:
                    doc = await cards_collection.find_one({"_id": card_id})
                    if doc:
                        # Merge DB doc with client-sent fields (preserve orientation/order)
                        doc_copy = {**doc}
                        if "_id" in doc_copy:
                            doc_copy["id"] = str(doc_copy.pop("_id"))
                        # Overlay client fields last so orientation/order are kept
                        enriched_cards.append({**doc_copy, **{k: v for k, v in c.items() if k not in ("_id",)}})
                        continue
            except Exception:
                pass
            enriched_cards.append(c)

        service = AIService()
        reading = await service.generate_tarot_reading(
            question=payload.question,
            cards_drawn=enriched_cards,
            reading_type=payload.reading_type or "general",
            detail=(payload.reading_detail or "quick"),
            llm_config=payload.llm_config.model_dump() if payload.llm_config else None
        )

        logger.info("Generated AI reading", question=payload.question[:50])
        return reading

    except Exception as e:
        logger.error("Failed to generate reading", error=str(e))
        raise HTTPException(status_code=500, detail="Failed to generate reading")


@router.post(
    "/generate-reading/stream",
    responses={
        200: {
            "content": {"text/plain": {"schema": {"type": "string", "example": "...streaming text..."}}},
            "description": "Plain text streaming of the AI reading",
        }
    },
    summary="Stream AI tarot reading",
    description="Stream the reading text progressively as it's generated by the LLM.",
)
async def generate_reading_stream(
    payload: GenerateReadingRequest,
    cards_collection: AsyncIOMotorCollection = Depends(get_tarot_cards_collection),
):
    """Stream AI reading text chunks as they are generated."""
    try:
        # Enrich cards
        enriched_cards = []
        for c in payload.cards:
            try:
                card_id = c.get("id") or c.get("_id")
                if card_id:
                    doc = await cards_collection.find_one({"_id": card_id})
                    if doc:
                        doc_copy = {**doc}
                        if "_id" in doc_copy:
                            doc_copy["id"] = str(doc_copy.pop("_id"))
                        enriched_cards.append({**doc_copy, **{k: v for k, v in c.items() if k not in ("_id",)}})
                        continue
            except Exception:
                pass
            enriched_cards.append(c)

        service = AIService()

        async def event_generator():
            async for chunk in service.stream_tarot_reading(
                question=payload.question,
                cards_drawn=enriched_cards,
                reading_type=payload.reading_type or "general",
                detail=(payload.reading_detail or "quick"),
                llm_config=payload.llm_config.model_dump() if payload.llm_config else None
            ):
                yield chunk
        return StreamingResponse(
            event_generator(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache, no-transform",
                "X-Accel-Buffering": "no",
                "Connection": "keep-alive",
            },
        )
    except Exception as e:
        logger.error("Failed to stream reading", error=str(e))
        raise HTTPException(status_code=500, detail="Failed to stream reading")

@router.post("/train-model")
async def train_model(
    training_data: list,
    collection: AsyncIOMotorCollection = Depends(get_ai_training_data_collection)
):
    """
    Train AI model with new data
    """
    try:
        service = AIService(collection)
        result = await service.train_model(training_data)
        
        logger.info("Trained AI model", data_count=len(training_data))
        return {"success": result}
        
    except Exception as e:
        logger.error("Failed to train model", error=str(e))
        raise HTTPException(status_code=500, detail="Failed to train model")


class IntakeRequest(BaseModel):
    question: str

@router.post("/intake", summary="Get spread recommendation (AutoHarness Router)")
async def intake_question(payload: IntakeRequest):
    """
    Classify user intent and return a recommended spread schema.
    """
    try:
        service = HarnessRouterService()
        result = await service.get_intake_recommendation(payload.question)
        return result
    except Exception as e:
        logger.error("Failed to process intake", error=str(e))
        raise HTTPException(status_code=500, detail="Failed to process intake router")
